#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 highbrige-yayoi
# SPDX-License-Identifier: BSD-3-Claus

import sys  

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
